[package]
name = "example-service-search"
version = "0.1.0"
authors = ["gian giovani <wejick@gmail.com>"]
license = "MIT"

[dependencies]
rs-es = "0.9.0"
serde = "0.9.0"
serde_derive = "0.9.0"
serde_json = "0.9.0"
router = "*"
iron = "*"